source("R/global_packages.R")
pkgconfig::set_config("drake::strings_in_dots" = "literals")
knitr::opts_knit$set(root.dir = "docs")
knitr::opts_knit$set(base.dir = "docs")
getwd()
source("R/global_functions.R")
source("R/multi2di_test.R")
source("R/plan.R")
source("R/plan_report.R")

make(Cetacea)
